spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://rm-bp14kjh9te20c7in93o.mysql.rds.aliyuncs.com/user_center?useSSL=false'
    username: hlllg
    password: HGL2020mm
  # session 失效时间
  session:
    timeout: 86400
server:
  address: 0.0.0.0
